apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: aws-auth-operator
  namespace: aws-auth-operator-system
spec:
  channel: stable
  installPlanApproval: Manual
  name: aws-auth-operator
  source: aws-auth-operator-catalog
  sourceNamespace: olm
  config:
    envFrom:
      - secretRef:
          name: aws-auth-operator-secret
