
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - auth.ops42.org
  resources:
  - awsauthsyncconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - auth.ops42.org
  resources:
  - awsauthsyncconfigs/finalizers
  verbs:
  - update
- apiGroups:
  - auth.ops42.org
  resources:
  - awsauthsyncconfigs/status
  verbs:
  - get
  - patch
  - update
