apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: aws-auth-operator-manager-rolebinding
  namespace: kube-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: aws-auth-operator-manager-role
subjects:
- kind: ServiceAccount
  name: aws-auth-operator-controller-manager
  namespace: aws-auth-operator-system
