name: Build Bundle and Catalog
on:
  push:
    branches:
      - main
jobs:
  Build-Image:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - run: cd ${{ github.workspace }}
      - run: echo "Building Image..."
      - run: |
          CHANNELS=stable
          DEFAULT_CHANNEL=stable
          make docker-build docker-push
      - run: echo "Job status is ${{ job.status }}."
