name: docs 

on:
  push:
    branches: 
      - main
jobs:
  Publish-Docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: |
          cd ${{ github.workspace }}
          pip install -r docs/requirements.txt
          mkdocs gh-deploy --force
