name: Create Release Draft

on: 
  push:
    branches:
      - main

jobs:
  Create-Release-Draft:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository code
      uses: actions/checkout@v2
    - name: Get Version
      run: |
        cd ${{ github.workspace }}
        echo "RELEASE_VERSION=v$(cat VERSION)" >> $GITHUB_ENV
    - uses: ncipollo/release-action@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        tag: ${{ env.RELEASE_VERSION }}
        commit: ${{ github.sha }}
        name: ${{ env.RELEASE_VERSION }}
        body: ${{ github.event.head_commit.message }}
        draft: true
