name: Test
on:
  push:
#    branches-ignore:
#      - main

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Running Tests
        run: make test

